apiVersion: v1
kind: Service
metadata:
  name: catholic-codes-website
  namespace: catholic-codes
spec:
  selector:
    app: catholic-codes-website
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
