apiVersion: v1
kind: Service
metadata:
  name: cybernetici
  namespace: catholic-codes
spec:
  selector:
    app: cybernetici
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: ClusterIP
